DROP DATABASE IF EXISTS BrainwaveDB;
CREATE DATABASE IF NOT EXISTS BrainwaveDB;
USE BrainwaveDB;

DROP TABLE IF EXISTS Studente;
CREATE TABLE IF NOT EXISTS Studente (
	Matricola INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(48) NOT NULL UNIQUE,
	password VARCHAR(48) NOT NULL,
	email VARCHAR(48) NOT NULL UNIQUE,
	nome VARCHAR(48) NOT NULL,
	cognome VARCHAR(48) NOT NULL,
	data_nascita  DATA NOT NULL;
);
DROP TABLE IF EXISTS Classe;
CREATE TABLE IF NOT EXISTS Classe (
	id_classe INT AUTO_INCREMENT PRIMARY KEY,
	anno int NOT NULL,
	sezione VARCHAR(48) NOT NULL,
	);
DROP TABLE IF EXISTS Scuola;
CREATE TABLE IF NOT EXISTS Scuola (
	id_scuola INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(48) NOT NULL UNIQUE,
	tipo VARCHAR(48) NOT NULL,
	descrizione VARCHAR(48),
	);
DROP TABLE IF EXISTS Lavora;
CREATE TABLE IF NOT EXISTS Lavora (
	id_scuola INT PRIMARY KEY,
	id_prof int PRIMARY KEY,
	);
DROP TABLE IF EXISTS Docente;
CREATE TABLE IF NOT EXISTS Docente (
	id_prof INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(48) NOT NULL UNIQUE,
	password VARCHAR(48) NOT NULL,
	email VARCHAR(48) NOT NULL UNIQUE,
	nome VARCHAR(48) NOT NULL,
	cognome VARCHAR(48) NOT NULL,
	data_nascita  DATA NOT NULL;
);
DROP TABLE IF EXISTS Tipo_Doc;
CREATE TABLE IF NOT EXISTS Tipo_Doc (
	id_tipod INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(48) NOT NULL,
	descrizione VARCHAR(48) NOT NULL,
	);
DROP TABLE IF EXISTS Documento;
CREATE TABLE IF NOT EXISTS Documento (
	id_documento INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(48) NOT NULL,
	);
DROP TABLE IF EXISTS Docente;
CREATE TABLE IF NOT EXISTS Docente (
	id_materia INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(48) NOT NULL UNIQUE,
	alias VARCHAR(48) NOT NULL,
	);
DROP TABLE IF EXISTS Tipo_Materia;
CREATE TABLE IF NOT EXISTS Tipo_Materia (
	id_materia INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(48) NOT NULL,
	descrizione VARCHAR(48) NOT NULL,
	);
DROP TABLE IF EXISTS Visualizza;
CREATE TABLE IF NOT EXISTS Visualizza (
	matricola INT PRIMARY KEY,
	id_documento int PRIMARY KEY
	);